Fix: TypeError: DQNAgent.sample_actions() got an unexpected keyword argument 'greedy'
Fixing the parameter missing of greedy:

```python
/tmp/ipython-input-3342619535.py in evaluate(env, agent, n_games, greedy, t_max, seed)
      6         reward = 0
      7         for _ in range(t_max):
----> 8             action = agent.sample_actions(np.array(s)[None], greedy=greedy)[0]
      9             s, r, terminated, truncated, _ = env.step(action)
     10             reward += r

TypeError: DQNAgent.sample_actions() got an unexpected keyword argument 'greedy'
```