ModuleNotFoundError: No module named 'atari_wrappers'
Atari Modules are not available to be downloaded from the current notebook. Therefore, I added the download links to them, besides the updated the `gym` environment to be compatible with them.

    # Update the gym environment to be compatible with the atari environment.